/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    merchandise: Merchandise;
    tenants: Tenant;
    'access-codes': AccessCode;
    'cash-transactions': CashTransaction;
    attendees: Attendee;
    'breakfast-tickets': BreakfastTicket;
    rooms: Room;
    'program-sessions': ProgramSession;
    'venue-maps': VenueMap;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    merchandise: MerchandiseSelect<false> | MerchandiseSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'access-codes': AccessCodesSelect<false> | AccessCodesSelect<true>;
    'cash-transactions': CashTransactionsSelect<false> | CashTransactionsSelect<true>;
    attendees: AttendeesSelect<false> | AttendeesSelect<true>;
    'breakfast-tickets': BreakfastTicketsSelect<false> | BreakfastTicketsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    'program-sessions': ProgramSessionsSelect<false> | ProgramSessionsSelect<true>;
    'venue-maps': VenueMapsSelect<false> | VenueMapsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Build public pages visually with the NECYPAA section library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * The same structured sections power the Payload form, visual builder, and public page.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            eventDate?: string | null;
            eventLocation?: string | null;
            /**
             * ISO date and time, including timezone.
             */
            countdownTarget?: string | null;
            registerLabel?: string | null;
            registerUrl?: string | null;
            hotelLabel?: string | null;
            hotelUrl?: string | null;
            /**
             * The transparent artwork layered in front of the hero.
             */
            foregroundImage?: (string | null) | Media;
            /**
             * Optional full-bleed image or muted looping video behind the hero.
             */
            backgroundImage?: (string | null) | Media;
            /**
             * Optional still image shown while a background video loads and when reduced motion is preferred.
             */
            backgroundPosterImage?: (string | null) | Media;
            /**
             * 0 leaves the background untouched; 100 applies the strongest readability overlay.
             */
            backgroundDarkness?: number | null;
            image?: (string | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'HeroCountdown';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            advisoryHeading?: string | null;
            advisoryBody?: string | null;
            image?: (string | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'About';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            date?: string | null;
            time?: string | null;
            location?: string | null;
            actionLabel?: string | null;
            actionUrl?: string | null;
            importantDates?:
              | {
                  date?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'MeetingInfo';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            upcomingLabel?: string | null;
            upcomingTitle?: string | null;
            upcomingBody?: string | null;
            upcomingDate?: string | null;
            upcomingLocation?: string | null;
            upcomingImage?: (string | null) | Media;
            pastEvents?:
              | {
                  title?: string | null;
                  date?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Events';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            meetings?:
              | {
                  name?: string | null;
                  location?: string | null;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'MeetingDirectory';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            primaryLabel?: string | null;
            primaryUrl?: string | null;
            secondaryLabel?: string | null;
            secondaryUrl?: string | null;
            image?: (string | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CallToAction';
          }
        | {
            image: string | Media;
            caption?: string | null;
            aspectRatio?: ('natural' | 'landscape' | 'portrait' | 'square') | null;
            width?: ('full' | 'wide' | 'content') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Image';
          }
        | {
            /**
             * Headings, links, lists, quotes, alignment, and inline formatting.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            fontSize?: string | null;
            color?: string | null;
            fontWeight?: ('400' | '700') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'RichText';
          }
        | {
            text?: string | null;
            fontSize?: string | null;
            color?: string | null;
            fontWeight?: ('400' | '700') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FreeText';
          }
        | {
            primaryLabel?: string | null;
            primaryUrl?: string | null;
            secondaryLabel?: string | null;
            secondaryUrl?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ButtonRow';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            issues?:
              | {
                  title?: string | null;
                  body?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'IssuesSection';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            variant?: ('cards' | 'editorial' | 'image') | null;
            cards?:
              | {
                  label?: string | null;
                  heading?: string | null;
                  body?: string | null;
                  image?: (string | null) | Media;
                  linkLabel?: string | null;
                  linkUrl?: string | null;
                  blocks?:
                    | (
                        | {
                            image: string | Media;
                            caption?: string | null;
                            aspectRatio?: ('natural' | 'landscape' | 'portrait' | 'square') | null;
                            width?: ('full' | 'wide' | 'content') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'Image';
                          }
                        | {
                            /**
                             * Headings, links, lists, quotes, alignment, and inline formatting.
                             */
                            content?: {
                              root: {
                                type: string;
                                children: {
                                  type: any;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            } | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'RichText';
                          }
                        | {
                            text?: string | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'FreeText';
                          }
                        | {
                            primaryLabel?: string | null;
                            primaryUrl?: string | null;
                            secondaryLabel?: string | null;
                            secondaryUrl?: string | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'ButtonRow';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'IssueCards';
          }
        | {
            heading?: string | null;
            quote?: string | null;
            attribution?: string | null;
            role?: string | null;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'QuoteBlock';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            stats?:
              | {
                  value?: string | null;
                  label?: string | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ResultsStats';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            logos?:
              | {
                  name?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SupporterLogos';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            tabs?:
              | {
                  label?: string | null;
                  description?: string | null;
                  blocks?:
                    | (
                        | {
                            image: string | Media;
                            caption?: string | null;
                            aspectRatio?: ('natural' | 'landscape' | 'portrait' | 'square') | null;
                            width?: ('full' | 'wide' | 'content') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'Image';
                          }
                        | {
                            /**
                             * Headings, links, lists, quotes, alignment, and inline formatting.
                             */
                            content?: {
                              root: {
                                type: string;
                                children: {
                                  type: any;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            } | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'RichText';
                          }
                        | {
                            text?: string | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'FreeText';
                          }
                        | {
                            primaryLabel?: string | null;
                            primaryUrl?: string | null;
                            secondaryLabel?: string | null;
                            secondaryUrl?: string | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'ButtonRow';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ActionTabs';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  image?: (string | null) | Media;
                  caption?: string | null;
                  size?: ('small' | 'medium' | 'large') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'MediaGallery';
          }
        | {
            layout?: ('one' | 'two' | 'leftWide' | 'rightWide' | 'three' | 'four') | null;
            columns?:
              | {
                  label?: string | null;
                  blocks?:
                    | (
                        | {
                            image: string | Media;
                            caption?: string | null;
                            aspectRatio?: ('natural' | 'landscape' | 'portrait' | 'square') | null;
                            width?: ('full' | 'wide' | 'content') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'Image';
                          }
                        | {
                            /**
                             * Headings, links, lists, quotes, alignment, and inline formatting.
                             */
                            content?: {
                              root: {
                                type: string;
                                children: {
                                  type: any;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            } | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'RichText';
                          }
                        | {
                            text?: string | null;
                            fontSize?: string | null;
                            color?: string | null;
                            fontWeight?: ('400' | '700') | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'FreeText';
                          }
                        | {
                            primaryLabel?: string | null;
                            primaryUrl?: string | null;
                            secondaryLabel?: string | null;
                            secondaryUrl?: string | null;
                            alignment?: ('left' | 'center' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'ButtonRow';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ContentRow';
          }
        | {
            heading?: string | null;
            introduction?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ProgramSchedule';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Compatibility mirror for pages created before structured layout blocks were added.
   */
  builderData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each entry is one sellable item and appears as one card in the merchandise portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise".
 */
export interface Merchandise {
  id: string;
  name: string;
  /**
   * Used in links. Example: escaping-the-mad-realm
   */
  slug: string;
  /**
   * Main product image shown in the merchandise portal.
   */
  image: string | Media;
  /**
   * A short description of the design. This text is searchable.
   */
  description: string;
  type: 't-shirt' | 'long-sleeve' | 'hoodie' | 'crewneck' | 'hat' | 'sticker' | 'pin' | 'tote' | 'mug' | 'other';
  /**
   * Price in dollars.
   */
  price: number;
  /**
   * Add one row for each sellable size/color combination. For items without sizes or colors, add one row and leave both blank.
   */
  inventory: {
    /**
     * Optional. Example: M or One size.
     */
    size?: string | null;
    /**
     * Optional. Example: Black.
     */
    color?: string | null;
    /**
     * Optional internal item code.
     */
    sku?: string | null;
    /**
     * Units currently available.
     */
    quantity: number;
    id?: string | null;
  }[];
  available?: boolean | null;
  /**
   * Optional comma-separated keywords visitors might search for.
   */
  searchTerms?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Branding shared by the homepage, registration, cash entry, merchandise, and cart.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Header logo. Leave blank to use the NECYPAA 36 fallback mark.
   */
  logo?: (string | null) | Media;
  logoAlt?: string | null;
  theme: {
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    primary: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    secondary: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    accent: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    background: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    surface: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    lightBackground: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    darkText: string;
    /**
     * Choose a color or paste an exact six-digit hex code.
     */
    lightText: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Codes that authorize recording an in-person cash order at /cash.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes".
 */
export interface AccessCode {
  id: string;
  code: string;
  active: boolean;
  maxRedemptions: number;
  redemptionCount: number;
  grantType: 'cash_order' | 'complimentary_registration' | 'door_scholarship';
  issuerSource?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-person cash orders recorded through the protected /cash form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-transactions".
 */
export interface CashTransaction {
  id: string;
  purchaserName: string;
  purchaserEmail: string;
  recordedValueCents: number;
  status: 'recorded' | 'voided';
  stripeCustomerId?: string | null;
  accessCode: string | AccessCode;
  order:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notificationStatus?: ('not_required' | 'sent' | 'pending_configuration' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The working convention roster: paid registrants, identified scholarship recipients, cash registrations, and manually managed expected attendees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendees".
 */
export interface Attendee {
  id: string;
  sourceKey: string;
  attendeeName: string;
  attendeeEmail: string;
  state: string;
  homegroupCommittee?: string | null;
  attendanceStatus: 'expected' | 'checked_in' | 'cancelled';
  attendanceBasis: 'self_registration' | 'scholarship_recipient' | 'manual_expected';
  accommodations?: string | null;
  interpretationNeeded?: boolean | null;
  mobilityAccessibility?: boolean | null;
  willingToServe?: boolean | null;
  purchaserName: string;
  purchaserEmail: string;
  registrationPriceCents: number;
  paymentSource: 'stripe' | 'cash' | 'manual';
  paymentStatus: 'pending' | 'paid' | 'recorded' | 'refunded' | 'disputed' | 'voided';
  dataOrigin: 'live_checkout' | 'stripe_webhook' | 'stripe_backfill' | 'cash_checkout' | 'manual';
  purchasedAt: string;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeChargeId?: string | null;
  stripeCustomerId?: string | null;
  cashTransaction?: (string | null) | CashTransaction;
  policyAcknowledgments: {
    status: 'pending' | 'signed' | 'waived';
    signatureName?: string | null;
    signedAt?: string | null;
    readPolicy?: boolean | null;
    understandQuestions?: boolean | null;
    acknowledgeBehavior?: boolean | null;
    understandAdmission?: boolean | null;
    understandReporting?: boolean | null;
    understandInvestigation?: boolean | null;
    signatureAgreement?: boolean | null;
  };
  /**
   * Internal roster notes. This field is editable in Payload and is not sent to Stripe.
   */
  notes?: string | null;
  rawMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per breakfast admission, including Stripe purchases, cash purchases, and Stripe backfills.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breakfast-tickets".
 */
export interface BreakfastTicket {
  id: string;
  sourceKey: string;
  ticketCode: string;
  breakfastDay: 'friday' | 'saturday' | 'sunday';
  status: 'valid' | 'used' | 'refunded' | 'voided';
  unitPriceCents: number;
  purchaserName: string;
  purchaserEmail: string;
  attendee?: (string | null) | Attendee;
  paymentSource: 'stripe' | 'cash';
  paymentStatus: 'paid' | 'recorded' | 'refunded' | 'disputed' | 'voided';
  dataOrigin: 'live_checkout' | 'stripe_webhook' | 'stripe_backfill' | 'cash_checkout';
  purchasedAt: string;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeChargeId?: string | null;
  stripeCustomerId?: string | null;
  cashTransaction?: (string | null) | CashTransaction;
  rawMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Convention rooms used by the public program and visual planning board.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: string;
  name: string;
  shortLabel: string;
  floor?: string | null;
  capacity?: number | null;
  accessible?: boolean | null;
  directions?: string | null;
  displayOrder: number;
  mapX?: number | null;
  mapY?: number | null;
  /**
   * Six-digit hex color used on the planning board.
   */
  color?: string | null;
  /**
   * Internal notes; never displayed publicly.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Schedule records shown on the public Program page and editable on the visual Program Board at /program-editor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-sessions".
 */
export interface ProgramSession {
  id: string;
  title: string;
  slug: string;
  sessionType: 'main_meeting' | 'panel' | 'workshop' | 'dance' | 'marathon' | 'affinity' | 'special_event';
  startAt: string;
  endAt: string;
  room: string | Room;
  shortDescription?: string | null;
  presenters?:
    | {
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  tracks?:
    | ('Recovery' | 'Service' | 'Unity' | 'Accessibility' | 'LGBTQ+' | 'BIPOC' | 'Al-Anon' | 'Spanish / bilingual')[]
    | null;
  language: string;
  audience?: string | null;
  /**
   * Public accessibility details, such as ASL, captions, or step-free access.
   */
  accessibility?: string | null;
  image?: (string | null) | Media;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'cancelled';
  /**
   * Committee-only notes; never displayed publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload a hotel floor plan here. Room markers use the X/Y positions stored on each Room.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-maps".
 */
export interface VenueMap {
  id: string;
  title: string;
  floor: string;
  image?: (string | null) | Media;
  altText: string;
  description?: string | null;
  status: 'draft' | 'published';
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  merchandise?: {
    /**
     * Allow clients to find merchandise.
     */
    find?: boolean | null;
    /**
     * Allow clients to create merchandise.
     */
    create?: boolean | null;
    /**
     * Allow clients to update merchandise.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete merchandise.
     */
    delete?: boolean | null;
  };
  tenants?: {
    /**
     * Allow clients to find tenants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tenants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tenants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tenants.
     */
    delete?: boolean | null;
  };
  accessCodes?: {
    /**
     * Allow clients to find access-codes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create access-codes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update access-codes.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete access-codes.
     */
    delete?: boolean | null;
  };
  cashTransactions?: {
    /**
     * Allow clients to find cash-transactions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create cash-transactions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update cash-transactions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete cash-transactions.
     */
    delete?: boolean | null;
  };
  attendees?: {
    /**
     * Allow clients to find attendees.
     */
    find?: boolean | null;
    /**
     * Allow clients to create attendees.
     */
    create?: boolean | null;
    /**
     * Allow clients to update attendees.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete attendees.
     */
    delete?: boolean | null;
  };
  breakfastTickets?: {
    /**
     * Allow clients to find breakfast-tickets.
     */
    find?: boolean | null;
    /**
     * Allow clients to create breakfast-tickets.
     */
    create?: boolean | null;
    /**
     * Allow clients to update breakfast-tickets.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete breakfast-tickets.
     */
    delete?: boolean | null;
  };
  rooms?: {
    /**
     * Allow clients to find rooms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create rooms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update rooms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete rooms.
     */
    delete?: boolean | null;
  };
  programSessions?: {
    /**
     * Allow clients to find program-sessions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create program-sessions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update program-sessions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete program-sessions.
     */
    delete?: boolean | null;
  };
  venueMaps?: {
    /**
     * Allow clients to find venue-maps.
     */
    find?: boolean | null;
    /**
     * Allow clients to create venue-maps.
     */
    create?: boolean | null;
    /**
     * Allow clients to update venue-maps.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete venue-maps.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'merchandise';
        value: string | Merchandise;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'access-codes';
        value: string | AccessCode;
      } | null)
    | ({
        relationTo: 'cash-transactions';
        value: string | CashTransaction;
      } | null)
    | ({
        relationTo: 'attendees';
        value: string | Attendee;
      } | null)
    | ({
        relationTo: 'breakfast-tickets';
        value: string | BreakfastTicket;
      } | null)
    | ({
        relationTo: 'rooms';
        value: string | Room;
      } | null)
    | ({
        relationTo: 'program-sessions';
        value: string | ProgramSession;
      } | null)
    | ({
        relationTo: 'venue-maps';
        value: string | VenueMap;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        HeroCountdown?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              eventDate?: T;
              eventLocation?: T;
              countdownTarget?: T;
              registerLabel?: T;
              registerUrl?: T;
              hotelLabel?: T;
              hotelUrl?: T;
              foregroundImage?: T;
              backgroundImage?: T;
              backgroundPosterImage?: T;
              backgroundDarkness?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        About?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              advisoryHeading?: T;
              advisoryBody?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        MeetingInfo?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              date?: T;
              time?: T;
              location?: T;
              actionLabel?: T;
              actionUrl?: T;
              importantDates?:
                | T
                | {
                    date?: T;
                    label?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        Events?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              upcomingLabel?: T;
              upcomingTitle?: T;
              upcomingBody?: T;
              upcomingDate?: T;
              upcomingLocation?: T;
              upcomingImage?: T;
              pastEvents?:
                | T
                | {
                    title?: T;
                    date?: T;
                    image?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        MeetingDirectory?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              meetings?:
                | T
                | {
                    name?: T;
                    location?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        CallToAction?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        Image?:
          | T
          | {
              image?: T;
              caption?: T;
              aspectRatio?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        RichText?:
          | T
          | {
              content?: T;
              fontSize?: T;
              color?: T;
              fontWeight?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        FreeText?:
          | T
          | {
              text?: T;
              fontSize?: T;
              color?: T;
              fontWeight?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        ButtonRow?:
          | T
          | {
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        IssuesSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              issues?:
                | T
                | {
                    title?: T;
                    body?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        IssueCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              variant?: T;
              cards?:
                | T
                | {
                    label?: T;
                    heading?: T;
                    body?: T;
                    image?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    blocks?:
                      | T
                      | {
                          Image?:
                            | T
                            | {
                                image?: T;
                                caption?: T;
                                aspectRatio?: T;
                                width?: T;
                                id?: T;
                                blockName?: T;
                              };
                          RichText?:
                            | T
                            | {
                                content?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          FreeText?:
                            | T
                            | {
                                text?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          ButtonRow?:
                            | T
                            | {
                                primaryLabel?: T;
                                primaryUrl?: T;
                                secondaryLabel?: T;
                                secondaryUrl?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        QuoteBlock?:
          | T
          | {
              heading?: T;
              quote?: T;
              attribution?: T;
              role?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        ResultsStats?:
          | T
          | {
              heading?: T;
              intro?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        SupporterLogos?:
          | T
          | {
              heading?: T;
              intro?: T;
              logos?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ActionTabs?:
          | T
          | {
              heading?: T;
              intro?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    description?: T;
                    blocks?:
                      | T
                      | {
                          Image?:
                            | T
                            | {
                                image?: T;
                                caption?: T;
                                aspectRatio?: T;
                                width?: T;
                                id?: T;
                                blockName?: T;
                              };
                          RichText?:
                            | T
                            | {
                                content?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          FreeText?:
                            | T
                            | {
                                text?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          ButtonRow?:
                            | T
                            | {
                                primaryLabel?: T;
                                primaryUrl?: T;
                                secondaryLabel?: T;
                                secondaryUrl?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        MediaGallery?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    size?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ContentRow?:
          | T
          | {
              layout?: T;
              columns?:
                | T
                | {
                    label?: T;
                    blocks?:
                      | T
                      | {
                          Image?:
                            | T
                            | {
                                image?: T;
                                caption?: T;
                                aspectRatio?: T;
                                width?: T;
                                id?: T;
                                blockName?: T;
                              };
                          RichText?:
                            | T
                            | {
                                content?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          FreeText?:
                            | T
                            | {
                                text?: T;
                                fontSize?: T;
                                color?: T;
                                fontWeight?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                          ButtonRow?:
                            | T
                            | {
                                primaryLabel?: T;
                                primaryUrl?: T;
                                secondaryLabel?: T;
                                secondaryUrl?: T;
                                alignment?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ProgramSchedule?:
          | T
          | {
              heading?: T;
              introduction?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  builderData?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise_select".
 */
export interface MerchandiseSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  type?: T;
  price?: T;
  inventory?:
    | T
    | {
        size?: T;
        color?: T;
        sku?: T;
        quantity?: T;
        id?: T;
      };
  available?: T;
  searchTerms?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoAlt?: T;
  theme?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
        background?: T;
        surface?: T;
        lightBackground?: T;
        darkText?: T;
        lightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes_select".
 */
export interface AccessCodesSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  maxRedemptions?: T;
  redemptionCount?: T;
  grantType?: T;
  issuerSource?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-transactions_select".
 */
export interface CashTransactionsSelect<T extends boolean = true> {
  purchaserName?: T;
  purchaserEmail?: T;
  recordedValueCents?: T;
  status?: T;
  stripeCustomerId?: T;
  accessCode?: T;
  order?: T;
  metadata?: T;
  notificationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendees_select".
 */
export interface AttendeesSelect<T extends boolean = true> {
  sourceKey?: T;
  attendeeName?: T;
  attendeeEmail?: T;
  state?: T;
  homegroupCommittee?: T;
  attendanceStatus?: T;
  attendanceBasis?: T;
  accommodations?: T;
  interpretationNeeded?: T;
  mobilityAccessibility?: T;
  willingToServe?: T;
  purchaserName?: T;
  purchaserEmail?: T;
  registrationPriceCents?: T;
  paymentSource?: T;
  paymentStatus?: T;
  dataOrigin?: T;
  purchasedAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  stripeCustomerId?: T;
  cashTransaction?: T;
  policyAcknowledgments?:
    | T
    | {
        status?: T;
        signatureName?: T;
        signedAt?: T;
        readPolicy?: T;
        understandQuestions?: T;
        acknowledgeBehavior?: T;
        understandAdmission?: T;
        understandReporting?: T;
        understandInvestigation?: T;
        signatureAgreement?: T;
      };
  notes?: T;
  rawMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breakfast-tickets_select".
 */
export interface BreakfastTicketsSelect<T extends boolean = true> {
  sourceKey?: T;
  ticketCode?: T;
  breakfastDay?: T;
  status?: T;
  unitPriceCents?: T;
  purchaserName?: T;
  purchaserEmail?: T;
  attendee?: T;
  paymentSource?: T;
  paymentStatus?: T;
  dataOrigin?: T;
  purchasedAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  stripeCustomerId?: T;
  cashTransaction?: T;
  rawMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  shortLabel?: T;
  floor?: T;
  capacity?: T;
  accessible?: T;
  directions?: T;
  displayOrder?: T;
  mapX?: T;
  mapY?: T;
  color?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-sessions_select".
 */
export interface ProgramSessionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sessionType?: T;
  startAt?: T;
  endAt?: T;
  room?: T;
  shortDescription?: T;
  presenters?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  tracks?: T;
  language?: T;
  audience?: T;
  accessibility?: T;
  image?: T;
  featured?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-maps_select".
 */
export interface VenueMapsSelect<T extends boolean = true> {
  title?: T;
  floor?: T;
  image?: T;
  altText?: T;
  description?: T;
  status?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  merchandise?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  tenants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  accessCodes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  cashTransactions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  attendees?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  breakfastTickets?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  rooms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  programSessions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  venueMaps?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}