/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    merchandise: Merchandise;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    merchandise: MerchandiseSelect<false> | MerchandiseSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Build public pages visually with the NECYPAA section library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * The same structured sections power the Payload form, visual builder, and public page.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            eventDate?: string | null;
            eventLocation?: string | null;
            /**
             * ISO date and time, including timezone.
             */
            countdownTarget?: string | null;
            registerLabel?: string | null;
            registerUrl?: string | null;
            hotelLabel?: string | null;
            hotelUrl?: string | null;
            /**
             * The transparent artwork layered in front of the hero.
             */
            foregroundImage?: (number | null) | Media;
            /**
             * Optional full-bleed image or muted looping video behind the hero.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Optional still image shown while a background video loads and when reduced motion is preferred.
             */
            backgroundPosterImage?: (number | null) | Media;
            /**
             * 0 leaves the background untouched; 100 applies the strongest readability overlay.
             */
            backgroundDarkness?: number | null;
            image?: (number | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'HeroCountdown';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            advisoryHeading?: string | null;
            advisoryBody?: string | null;
            image?: (number | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'About';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            date?: string | null;
            time?: string | null;
            location?: string | null;
            actionLabel?: string | null;
            actionUrl?: string | null;
            importantDates?:
              | {
                  date?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'MeetingInfo';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            upcomingLabel?: string | null;
            upcomingTitle?: string | null;
            upcomingBody?: string | null;
            upcomingDate?: string | null;
            upcomingLocation?: string | null;
            upcomingImage?: (number | null) | Media;
            pastEvents?:
              | {
                  title?: string | null;
                  date?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Events';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            meetings?:
              | {
                  name?: string | null;
                  location?: string | null;
                  id?: string | null;
                }[]
              | null;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'MeetingDirectory';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            primaryLabel?: string | null;
            primaryUrl?: string | null;
            secondaryLabel?: string | null;
            secondaryUrl?: string | null;
            image?: (number | null) | Media;
            textStyles?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CallToAction';
          }
        | {
            image: number | Media;
            caption?: string | null;
            aspectRatio?: ('natural' | 'landscape' | 'portrait' | 'square') | null;
            width?: ('full' | 'wide' | 'content') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Image';
          }
        | {
            /**
             * Headings, links, lists, quotes, alignment, and inline formatting.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            fontSize?: string | null;
            color?: string | null;
            fontWeight?: ('400' | '700') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'RichText';
          }
        | {
            text?: string | null;
            fontSize?: string | null;
            color?: string | null;
            fontWeight?: ('400' | '700') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FreeText';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Compatibility mirror for pages created before structured layout blocks were added.
   */
  builderData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each entry is one sellable item and appears as one card in the merchandise portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise".
 */
export interface Merchandise {
  id: number;
  name: string;
  /**
   * Used in links. Example: escaping-the-mad-realm
   */
  slug: string;
  /**
   * Main product image shown in the merchandise portal.
   */
  image: number | Media;
  /**
   * A short description of the design. This text is searchable.
   */
  description: string;
  type: 't-shirt' | 'long-sleeve' | 'hoodie' | 'crewneck' | 'hat' | 'sticker' | 'pin' | 'tote' | 'mug' | 'other';
  /**
   * Price in dollars.
   */
  price: number;
  /**
   * Optional. Example: S–3XL or One size.
   */
  sizes?: string | null;
  available?: boolean | null;
  /**
   * Optional comma-separated keywords visitors might search for.
   */
  searchTerms?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'merchandise';
        value: number | Merchandise;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        HeroCountdown?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              eventDate?: T;
              eventLocation?: T;
              countdownTarget?: T;
              registerLabel?: T;
              registerUrl?: T;
              hotelLabel?: T;
              hotelUrl?: T;
              foregroundImage?: T;
              backgroundImage?: T;
              backgroundPosterImage?: T;
              backgroundDarkness?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        About?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              advisoryHeading?: T;
              advisoryBody?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        MeetingInfo?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              date?: T;
              time?: T;
              location?: T;
              actionLabel?: T;
              actionUrl?: T;
              importantDates?:
                | T
                | {
                    date?: T;
                    label?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        Events?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              upcomingLabel?: T;
              upcomingTitle?: T;
              upcomingBody?: T;
              upcomingDate?: T;
              upcomingLocation?: T;
              upcomingImage?: T;
              pastEvents?:
                | T
                | {
                    title?: T;
                    date?: T;
                    image?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        MeetingDirectory?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              meetings?:
                | T
                | {
                    name?: T;
                    location?: T;
                    id?: T;
                  };
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        CallToAction?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryLabel?: T;
              primaryUrl?: T;
              secondaryLabel?: T;
              secondaryUrl?: T;
              image?: T;
              textStyles?: T;
              id?: T;
              blockName?: T;
            };
        Image?:
          | T
          | {
              image?: T;
              caption?: T;
              aspectRatio?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        RichText?:
          | T
          | {
              content?: T;
              fontSize?: T;
              color?: T;
              fontWeight?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        FreeText?:
          | T
          | {
              text?: T;
              fontSize?: T;
              color?: T;
              fontWeight?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  builderData?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise_select".
 */
export interface MerchandiseSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  type?: T;
  price?: T;
  sizes?: T;
  available?: T;
  searchTerms?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}