CREATE TABLE `payload_mcp_api_keys` (
	`id` integer PRIMARY KEY NOT NULL,
	`user_id` integer NOT NULL,
	`label` text,
	`description` text,
	`users_find` integer DEFAULT false,
	`users_create` integer DEFAULT false,
	`users_update` integer DEFAULT false,
	`users_delete` integer DEFAULT false,
	`media_find` integer DEFAULT false,
	`media_create` integer DEFAULT false,
	`media_update` integer DEFAULT false,
	`media_delete` integer DEFAULT false,
	`pages_find` integer DEFAULT false,
	`pages_create` integer DEFAULT false,
	`pages_update` integer DEFAULT false,
	`pages_delete` integer DEFAULT false,
	`merchandise_find` integer DEFAULT false,
	`merchandise_create` integer DEFAULT false,
	`merchandise_update` integer DEFAULT false,
	`merchandise_delete` integer DEFAULT false,
	`tenants_find` integer DEFAULT false,
	`tenants_create` integer DEFAULT false,
	`tenants_update` integer DEFAULT false,
	`tenants_delete` integer DEFAULT false,
	`access_codes_find` integer DEFAULT false,
	`access_codes_create` integer DEFAULT false,
	`access_codes_update` integer DEFAULT false,
	`access_codes_delete` integer DEFAULT false,
	`cash_transactions_find` integer DEFAULT false,
	`cash_transactions_create` integer DEFAULT false,
	`cash_transactions_update` integer DEFAULT false,
	`cash_transactions_delete` integer DEFAULT false,
	`attendees_find` integer DEFAULT false,
	`attendees_create` integer DEFAULT false,
	`attendees_update` integer DEFAULT false,
	`attendees_delete` integer DEFAULT false,
	`breakfast_tickets_find` integer DEFAULT false,
	`breakfast_tickets_create` integer DEFAULT false,
	`breakfast_tickets_update` integer DEFAULT false,
	`breakfast_tickets_delete` integer DEFAULT false,
	`rooms_find` integer DEFAULT false,
	`rooms_create` integer DEFAULT false,
	`rooms_update` integer DEFAULT false,
	`rooms_delete` integer DEFAULT false,
	`program_sessions_find` integer DEFAULT false,
	`program_sessions_create` integer DEFAULT false,
	`program_sessions_update` integer DEFAULT false,
	`program_sessions_delete` integer DEFAULT false,
	`venue_maps_find` integer DEFAULT false,
	`venue_maps_create` integer DEFAULT false,
	`venue_maps_update` integer DEFAULT false,
	`venue_maps_delete` integer DEFAULT false,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`enable_a_p_i_key` integer,
	`api_key` text,
	`api_key_index` text,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `payload_mcp_api_keys_user_idx` ON `payload_mcp_api_keys` (`user_id`);--> statement-breakpoint
CREATE INDEX `payload_mcp_api_keys_updated_at_idx` ON `payload_mcp_api_keys` (`updated_at`);--> statement-breakpoint
CREATE INDEX `payload_mcp_api_keys_created_at_idx` ON `payload_mcp_api_keys` (`created_at`);--> statement-breakpoint
ALTER TABLE `payload_locked_documents_rels` ADD `payload_mcp_api_keys_id` integer REFERENCES payload_mcp_api_keys(id);--> statement-breakpoint
CREATE INDEX `payload_locked_documents_rels_payload_mcp_api_keys_id_idx` ON `payload_locked_documents_rels` (`payload_mcp_api_keys_id`);--> statement-breakpoint
ALTER TABLE `payload_preferences_rels` ADD `payload_mcp_api_keys_id` integer REFERENCES payload_mcp_api_keys(id);--> statement-breakpoint
CREATE INDEX `payload_preferences_rels_payload_mcp_api_keys_id_idx` ON `payload_preferences_rels` (`payload_mcp_api_keys_id`);