import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const base = process.env.HEADER_NAVIGATION_TEST_URL || 'http://127.0.0.1:3038';
if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(base)) throw new Error('Use only the disposable local header-navigation-fixture app.');
const evidence = process.env.HEADER_NAVIGATION_EVIDENCE || '/tmp/ypaa-header-navigation-evidence';
await mkdir(evidence, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.HEADER_NAVIGATION_CHROMIUM_EXECUTABLE ? { executablePath: process.env.HEADER_NAVIGATION_CHROMIUM_EXECUTABLE } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error' || message.type() === 'warning') errors.push(message.text()); });
const expanded = async (toggle, value) => {
  await toggle.page().waitForFunction(([node, expected]) => node.getAttribute('aria-expanded') === expected, [await toggle.elementHandle(), String(value)], { timeout: 5000 });
  assert.equal(await toggle.getAttribute('aria-expanded'), String(value));
};
const focus = async (locator) => {
  await locator.page().waitForFunction((node) => node === document.activeElement, await locator.elementHandle(), { timeout: 5000 });
  assert.equal(await locator.evaluate((node) => node === document.activeElement), true);
};
const primary = page.getByRole('navigation', { name: 'Primary navigation', exact: true });
const first = primary.getByRole('button', { name: 'Child links for Parent', exact: true });
const second = primary.getByRole('button', { name: 'Child links for Second parent', exact: true });
try {
  await page.goto(base);
  await page.getByRole('heading', { name: 'Header navigation QA fixture', exact: true }).waitFor();
  assert.equal(new URL(page.url()).origin, base);
  assert.equal(await page.title(), 'Header navigation QA fixture');
  assert.equal(await page.locator('nextjs-portal').filter({ hasText: /error/i }).count(), 0);
  await expanded(first, false);
  assert.equal(await primary.getByRole('link', { name: 'Child one', exact: true }).count(), 0);
  assert.equal(await primary.getByRole('button').count(), 2, 'Flat and empty groups have no toggle');
  await primary.getByRole('link', { name: 'Parent', exact: true }).click();
  await page.waitForURL(/#parent$/);
  assert.equal(new URL(page.url()).hash, '#parent');
  await expanded(first, false);
  await first.focus(); await first.press('Enter'); await expanded(first, true); await focus(first);
  await first.press('Tab'); await focus(primary.getByRole('link', { name: 'Child one', exact: true }));
  await page.keyboard.press('Escape'); await expanded(first, false); await focus(first);
  await first.press('Space'); await expanded(first, true);
  await first.press('ArrowDown'); await focus(primary.getByRole('link', { name: 'Child one', exact: true }));
  await page.keyboard.press('Escape'); await first.press('ArrowUp'); await focus(primary.getByRole('link', { name: /Warning child/ }));
  assert.equal(await primary.getByRole('link', { name: /External child/ }).getAttribute('target'), '_blank');
  assert.equal(await primary.getByRole('link', { name: /External child/ }).getAttribute('rel'), 'noreferrer');
  assert.equal(await primary.getByRole('link', { name: 'Disabled child' }).count(), 0);
  assert.equal(await primary.getByRole('link', { name: 'Invalid child' }).count(), 0);
  await primary.getByRole('link', { name: /Warning child/ }).click();
  await page.getByRole('dialog', { name: 'You are leaving this site' }).waitFor();
  await page.getByRole('button', { name: 'Stay here', exact: true }).click();
  await focus(primary.getByRole('link', { name: /Warning child/ }));
  await page.keyboard.press('Escape');
  await first.click(); await second.click(); await expanded(first, false); await expanded(second, true);
  await page.getByRole('button', { name: 'Outside control' }).click(); await expanded(second, false);
  await first.click(); await primary.getByRole('link', { name: 'Flat link', exact: true }).focus(); await expanded(first, false);
  await first.click(); await primary.getByRole('link', { name: 'Child one', exact: true }).click();
  await page.waitForURL(/#child-one$/);
  assert.equal(new URL(page.url()).hash, '#child-one'); await expanded(first, false);
  await first.click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  await page.screenshot({ path: `${evidence}/desktop.png`, fullPage: false });
  await page.setViewportSize({ width: 390, height: 844 });
  const menu = page.getByRole('button', { name: 'Open navigation', exact: true });
  await menu.click();
  const mobile = page.getByRole('navigation', { name: 'Mobile navigation', exact: true });
  const toggle = mobile.getByRole('button', { name: 'Child links for Parent', exact: true });
  await focus(mobile.getByRole('link', { name: 'Parent', exact: true }));
  await toggle.click(); await expanded(toggle, true);
  await mobile.getByRole('link', { name: 'Child one', exact: true }).focus();
  await page.keyboard.press('Escape'); await expanded(toggle, false); await focus(toggle);
  assert.equal(await mobile.isVisible(), true, 'First Escape closes the group only');
  await page.keyboard.press('Escape');
  await focus(page.getByRole('button', { name: 'Open navigation', exact: true }));
  assert.equal(await mobile.count(), 0, 'Second Escape closes the whole mobile menu');
  await menu.click(); await toggle.click();
  await mobile.getByRole('link', { name: /Warning child/ }).click();
  await page.getByRole('button', { name: 'Stay here', exact: true }).click();
  await focus(mobile.getByRole('link', { name: /Warning child/ }));
  assert.equal(await mobile.isVisible(), true, 'Warning cancellation keeps a focusable navigation target');
  await mobile.getByRole('link', { name: /Warning child/ }).click();
  await page.getByRole('dialog', { name: 'You are leaving this site' }).waitFor();
  await page.keyboard.press('Escape');
  await focus(mobile.getByRole('link', { name: /Warning child/ }));
  assert.equal(await mobile.isVisible(), true, 'Dialog Escape must not close the underlying mobile panel');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  await page.screenshot({ path: `${evidence}/mobile.png`, fullPage: false });
  await mobile.getByRole('link', { name: 'Child two', exact: true }).click();
  await page.waitForURL(/#child-two$/);
  assert.equal(new URL(page.url()).hash, '#child-two'); assert.equal(await mobile.count(), 0);
  await menu.click(); await toggle.click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await mobile.waitFor({ state: 'detached' });
  assert.equal(await mobile.count(), 0); await expanded(first, false);
  await page.getByRole('button', { name: 'Display and accessibility settings', exact: true }).click();
  await page.getByRole('button', { name: 'Light', exact: true }).click();
  await page.getByLabel('Extra contrast', { exact: true }).check();
  await page.getByRole('button', { name: 'Close display settings', exact: true }).click();
  await first.click(); await page.screenshot({ path: `${evidence}/light-contrast.png`, fullPage: false });
  const touchContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const touchPage = await touchContext.newPage();
  touchPage.on('pageerror', (error) => errors.push(error.message));
  await touchPage.goto(base);
  await touchPage.getByRole('button', { name: 'Open navigation', exact: true }).tap();
  const touchNav = touchPage.getByRole('navigation', { name: 'Mobile navigation', exact: true });
  const touchToggle = touchNav.getByRole('button', { name: 'Child links for Parent', exact: true });
  await touchToggle.tap(); await expanded(touchToggle, true);
  await touchToggle.tap(); await expanded(touchToggle, false);
  await touchToggle.tap(); await touchNav.getByRole('link', { name: 'Child one', exact: true }).tap();
  await touchPage.waitForURL(/#child-one$/);
  assert.equal(new URL(touchPage.url()).hash, '#child-one'); assert.equal(await touchNav.count(), 0);
  await touchContext.close();
  assert.deepEqual(errors, [], 'No console, hydration, duplicate-key or runtime errors');
  console.log(JSON.stringify({ status: 'passed', url: base, viewports: ['1440x1000', '390x844', '390x844 touch'], checks: ['identity', 'meaningful content', 'no overlay', 'console clean', 'keyboard', 'focus', 'Escape', 'outside click', 'parent link', 'child navigation', 'warning cancellation', 'new-tab semantics', 'flat fallback', 'invalid and disabled children', 'resize reset', 'light contrast', 'touch tap', 'screenshots'], evidence }, null, 2));
} finally { await context.close(); await browser.close(); }
