// Browser plugin not available. This separate headless browser touches synthetic localhost only.
import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { chromium } from 'playwright';
import { MongoClient } from 'mongodb';

const base = 'http://127.0.0.1:3029', screenshots = '/tmp/necypaa-hotel-qa';
const uri = new URL(process.env.DATABASE_URI || '');
assert.equal(uri.hostname, '127.0.0.1'); assert.equal(uri.pathname, '/ypaa_registration_test');
assert.equal(process.env.REGISTRATION_TEST_MAIL_CAPTURE, 'true');
const client = new MongoClient(uri.href); await client.connect();
const db = client.db(); assert.equal((await db.collection('_synthetic_test_marker').findOne({ _id: 'registration' }))?.synthetic, true);
await db.collection('_hotel_request_limits').deleteMany({});
await mkdir(screenshots, { recursive: true });
const mail = async () => (await readFile('.local-registration/mail.ndjson', 'utf8')).split('\n').filter(Boolean).map((line) => JSON.parse(line));
const run = randomUUID().slice(0, 8), email = `hotel-browser-${run}@example.invalid`;
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
const page = await context.newPage(); page.setDefaultTimeout(180000); page.setDefaultNavigationTimeout(240000);
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error' && !/503|403|429/.test(message.text())) errors.push(message.text()); });
try {
  assert.deepEqual(await (await context.request.get(`${base}/api/hotel-request`, { timeout: 180000 })).json(), { acceptingRequests: true });
  await page.goto(`${base}/hotel-request-test`);
  const button = page.getByRole('button', { name: 'Send hotel request', exact: true });
  await button.waitFor(); await page.waitForFunction(() => ![...document.querySelectorAll('button')].find((node) => node.textContent.includes('Send hotel request'))?.disabled);
  assert.equal(new URL(page.url()).pathname, '/hotel-request-test'); assert.ok(await page.title());
  assert.equal(await page.locator('nextjs-portal').filter({ hasText: /error/i }).count(), 0);
  const heading = page.getByRole('heading', { name: 'Need help with a hotel room?' });
  const headingBounds = await heading.boundingBox(), headerBounds = await page.locator('.cms-header').boundingBox();
  assert.ok(headingBounds.y >= headerBounds.y + headerBounds.height, 'Heading clears fixed site header');
  await page.getByLabel('Your name', { exact: true }).fill('Synthetic Hotel Guest');
  await page.getByLabel('Email address', { exact: true }).fill('bad-email'); await button.click();
  assert.equal(await page.getByLabel('Email address', { exact: true }).evaluate((node) => node.validity.valid), false);
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Phone number', { exact: true }).fill('860-555-0100');
  await page.getByLabel('Arrival date', { exact: true }).fill('2026-12-31');
  await page.getByLabel('Departure date', { exact: true }).fill('2026-12-31');
  await button.click(); await page.getByRole('alert').filter({ hasText: 'Choose valid arrival and departure dates' }).waitFor();
  await page.getByLabel('Departure date', { exact: true }).fill('2027-01-03');
  await page.getByLabel('Number of rooms', { exact: true }).fill('2');
  await page.getByLabel('Anything else we should know?', { exact: false }).fill('Synthetic request: please contact me about available options.');
  await page.screenshot({ path: `${screenshots}/desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => window.scrollTo(0, 0));
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  await page.screenshot({ path: `${screenshots}/mobile.png`, fullPage: true });
  await page.route('**/api/hotel-request', (route) => route.request().method() === 'POST' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Synthetic storage failure. Please retry.' }) }) : route.continue());
  await button.click(); await page.getByRole('alert').filter({ hasText: 'Synthetic storage failure' }).waitFor(); assert.equal(await button.isEnabled(), true);
  await page.unroute('**/api/hotel-request');
  // Respect the real minimum form-age control even on a fully warmed app.
  await page.waitForTimeout(1600);
  const before = (await mail()).length;
  await button.dblclick(); await page.getByRole('button', { name: 'Request saved', exact: true }).waitFor();
  await page.getByRole('status').filter({ hasText: 'This is a request, not a confirmed booking' }).waitFor();
  const record = await db.collection('hotel-requests').findOne({ email });
  assert.ok(record); assert.equal(record.status, 'new'); assert.equal(record.notificationStatus, 'sent'); assert.equal(record.numberOfRooms, 2);
  assert.deepEqual(record.requestedNights.map((night) => night.date), ['2026-12-31', '2027-01-01', '2027-01-02']);
  assert.equal((await db.collection('hotel-requests').countDocuments({ email })), 1);
  const sent = (await mail()).slice(before); assert.equal(sent.length, 1); assert.equal(sent[0].to, 'hotel-chair@example.invalid');
  await page.screenshot({ path: `${screenshots}/saved-mobile.png`, fullPage: true });
  const anonymous = await browser.newContext(); assert.equal((await anonymous.request.get(`${base}/api/hotel-requests/${record._id}`, { timeout: 180000 })).status(), 403); await anonymous.close();
  await page.setViewportSize({ width: 1440, height: 1000 });
  const login = await context.request.post(`${base}/api/users/login`, { data: { email: 'browser-admin@example.invalid', password: 'LocalSyntheticBrowserOnly123!' }, timeout: 180000 }); assert.equal(login.status(), 200);
  const queue = await context.request.get(`${base}/api/hotel-requests?where[email][equals]=${encodeURIComponent(email)}`, { timeout: 180000 });
  assert.equal(queue.status(), 200); assert.equal((await queue.json()).docs.length, 1, 'Private collection REST list remains available');
  console.log('Public form, durable save, captured notification and private REST access checks passed.');
  await page.goto(`${base}/admin/collections/hotel-requests`);
  await page.getByText('Synthetic Hotel Guest', { exact: true }).first().waitFor();
  await page.goto(`${base}/admin/collections/hotel-requests/${record._id}`);
  await page.getByRole('button', { name: 'Retry organizer notification', exact: true }).waitFor();
  console.log('Private admin request detail loaded; checking notification retry.');
  const beforeRetry = (await mail()).length;
  await page.getByRole('button', { name: 'Retry organizer notification', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Notification status: sent' }).waitFor(); assert.equal((await mail()).length, beforeRetry, 'Already accepted recipient is skipped');
  await page.screenshot({ path: `${screenshots}/private-queue.png`, fullPage: true });
  console.log('Admin retry passed without another organizer email.');
  const editorPage = await context.request.post(`${base}/api/pages`, { timeout: 180000, data: { title: 'Synthetic hotel editor test', slug: `hotel-editor-${run}`, _status: 'draft', layout: [{ blockType: 'HotelRequest', heading: 'Need help with a hotel room?', intro: 'Synthetic editor preview.' }] } });
  assert.equal(editorPage.status(), 201);
  const testPage = { _id: (await editorPage.json()).doc.id };
  await page.goto(`${base}/admin/visual-builder/${testPage._id}`);
  await page.getByText('Visual builder', { exact: true }).waitFor();
  console.log('Puck editor loaded; checking disabled preview and editable introduction.');
  const frame = page.frameLocator('iframe').first();
  await frame.getByRole('heading', { name: 'Need help with a hotel room?' }).waitFor();
  assert.equal(await frame.getByRole('button', { name: 'Send hotel request', exact: true }).isDisabled(), true);
  await frame.getByRole('heading', { name: 'Need help with a hotel room?' }).click();
  // This app places Puck fields in its own left-sidebar plugin tab.
  await page.locator('nav').getByText('Fields', { exact: true }).click();
  await page.getByLabel('Heading', { exact: true }).fill('Hotel plans, made easier');
  await page.getByLabel('Introduction / description', { exact: false }).fill('Your editable introduction.\nThe committee will follow up about options.');
  await frame.getByRole('heading', { name: 'Hotel plans, made easier' }).waitFor();
  await frame.getByText('Your editable introduction.', { exact: false }).waitFor();
  await page.getByText('Saved', { exact: true }).waitFor();
  const savedDraft = await context.request.get(`${base}/api/pages/${testPage._id}?draft=true`, { timeout: 180000 }); assert.equal(savedDraft.status(), 200);
  const data = await savedDraft.json(); assert.equal(data.layout[0].heading, 'Hotel plans, made easier'); assert.equal(data.layout[0].intro, 'Your editable introduction.\nThe committee will follow up about options.'); assert.equal("acceptingRequests" in data.layout[0], false);
  await page.screenshot({ path: `${screenshots}/editor-desktop.png`, fullPage: false });
  await page.getByRole('button', { name: 'Preview light theme' }).click();
  assert.equal(await frame.getByRole('button', { name: 'Send hotel request', exact: true }).isDisabled(), true);
  await page.screenshot({ path: `${screenshots}/editor-light.png`, fullPage: false });
  await page.getByTitle("Switch to Mobile viewport", { exact: true }).click();
  await page.waitForFunction(() => document.querySelector("iframe")?.getBoundingClientRect().width <= 400);
  assert.ok(await frame.locator("body").evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: `${screenshots}/editor-mobile.png`, fullPage: false });
  // No publication: edits above are synthetic draft autosaves only.
  assert.deepEqual(errors, []);
  console.log('Hotel browser checks passed: working by default, page identity, nonblank/no overlay, labels, native/server validation, duplicate clicks, durable saved request, captured organizer email, failure recovery, private queue/retry, editable Puck description and disabled preview, desktop/mobile layouts, no runtime errors.');
} catch (error) {
  await page.screenshot({ path: `${screenshots}/browser-failure.png`, fullPage: true }).catch(() => {});
  console.error('Browser failure at', page.url(), '\n', (await page.locator('body').innerText().catch(() => '')).slice(-5000));
  throw error;
} finally { await browser.close(); await client.close(); }
